# Generated by Django 5.0.6 on 2024-07-04 12:30

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawntransaction',
            name='pawn_expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 12, 30, 35, 5574, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='pawntransaction',
            name='pawn_renewal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pawntransaction',
            name='pawn_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
